### PR TITLE
AMD/NPM support

### PR DESCRIPTION
**Pull request by darul75**
Hi,
I propose the following AMD support to be published then to npm.
What do you think about it ?
I am using your library for a webpack project and think it will be useful.
Julien

### CODE REVIEW

**Comment by Victa** [comment]
Hey @darul75 

thanks for your pull request. I don't really maintain this project anymore but i'm okay to merge :+1:

**Comment by darul75** [comment]
your work was just enough to use it and solution is great for parallax

Can you push it on npm then ?

**Comment by Victa** [comment]
https://www.npmjs.com/package/jquery.scrolly

**Comment by darul75** [comment]
great, thx, let's fight with webpack again now...thanks for being reactive. I come back to you if some needs

**Pull request merged**
